### ISSUE TITLE
Using other model with checkpoint

### ISSUE THREAD

**Issue by 25icecreamflavors** [goel-shashank/CyCLIP#5]
Hello, in your example you use RN50 with your checkpoint weights. Is it possible to load, for example, ViT14 and use your checkpoints? Or there checkpoints only for RN50?

**Comment by Hritikbansal** [comment]
Hi, 

Unfortunately due to limited resources, we were only able to train CLIP and CyCLIP with RN50. Our initial experiments had suggested that CLIP trained with RN50 performs better than any other variants of visual encoders at our scales. 

Check out this issue for more discussion on this: https://github.com/mlfoundations/open_clip/issues/14

**Comment by Hritikbansal** [comment]
Hi,

Unfortunately due to limited resources, we were only able to train CLIP and CyCLIP with RN50. Our initial experiments had suggested that CLIP trained with RN50 performs better than any other variants of visual encoders at our scales.

Check out this issue for more discussion on this: https://github.com/mlfoundations/open_clip/issues/14

**Comment by 25icecreamflavors** [comment]
Thank you very much for your answer.
